name: runtest
on: push

jobs:
  install-gcc:
      name: install-gcc
      runs-on: ubuntu-latest
      steps:
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
          
  run-test:
    needs: install-gcc
    runs-on: ubuntu-latest
    steps:
      - name: run-file!
        env: 
          RAW: https://raw.githubusercontent.com/lianisok/Actions/main
          
        run: |
          ls
          wget https://raw.githubusercontent.com/lianisok/Actions/main/testfile/Test1.cpp
          gcc Test1.cpp -lstdc++ -o test
          .\test
        
